
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'linkmerce_postgres'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_postgres'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

quoting:
  database: false
  schema: false
  identifier: false

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  linkmerce_postgres:
    +persist_docs:
      relation: true
      columns: true
    +pre-hook:
      - "SET LOCAL max_parallel_workers_per_gather = 0"
      - "SET LOCAL enable_parallel_append = off"
    intermediate:
      +materialized: view
    marts:
      +materialized: table
